quest_create_mis goal_state_0, 0
quest_create_mis goal_visible_0, 1
quest_create_mis goal_type_0, 3
quest_create_mis goal_loot_0, 1000
quest_create_mis goal_max_diff_0, 0
quest_create_mis goal_state_1, 0
quest_create_mis goal_visible_1, 1
quest_create_mis goal_type_1, 3
quest_create_mis goal_loot_1, 1500
quest_create_mis goal_min_diff_1, 1
quest_create_mis goal_max_diff_1, 1
quest_create_mis goal_state_2, 0
quest_create_mis goal_visible_2, 1
quest_create_mis goal_type_2, 3
quest_create_mis goal_loot_2, 2000
quest_create_mis goal_min_diff_2, 2
quest_create_mis goal_state_3, 0
quest_create_mis goal_visible_3, 1
quest_create_mis goal_type_3, 1
quest_create_mis goal_target_3, 1426
quest_create_mis goal_state_4, 0
quest_create_mis goal_visible_4, 0
quest_create_mis goal_type_4, 1
quest_create_mis goal_target_4, 1134
quest_create_mis goal_state_5, 0
quest_create_mis goal_visible_5, 0
quest_create_mis goal_type_5, 1
quest_create_mis goal_target_5, 1250
quest_create_mis goal_min_diff_5, 1
quest_create_mis goal_state_6, 0
quest_create_mis goal_visible_6, 1
quest_create_mis goal_type_6, 1
quest_create_mis goal_target_6, 307
quest_create_mis goal_min_diff_6, 2
quest_create_mis goal_state_7, 0
quest_create_mis goal_visible_7, 0
quest_create_mis goal_type_7, 1
quest_create_mis goal_target_7, 875
quest_create_mis goal_min_diff_7, 2
quest_create_mis goal_state_8, 0
quest_create_mis goal_visible_8, 1
quest_create_mis goal_type_8, 2
quest_create_mis goal_target_8, -14
quest_create_mis goal_reverse_8, 1
quest_create_mis goal_min_diff_8, 1
quest_create_mis goal_state_9, 0
quest_create_mis goal_visible_9, 1
quest_create_mis goal_type_9, 4
quest_create_mis goal_target_9, 78
quest_create_mis goal_final_9, 1
